Change CSS cachebust to use a query parameter, rather than a completely separate file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -80,27 +80,34 @@ jobs:
           name: Checking CSS
           command: |
             CSS_FILE="./src/assets/css/main.css"
+            HTML_FILE="./src/views/base.html"
             MD5_HASH=$(md5sum "$CSS_FILE" | awk '{ print $1 }')
 
-            CACHE_BUSTED_CSS_FILE="./src/assets/css/main.${MD5_HASH}.css"
-            if [ ! -f "$CACHE_BUSTED_CSS_FILE" ]; then
-              echo "Error: Cache busted CSS file not found at $CACHE_BUSTED_CSS_FILE"
+            if [ ! -f "$CSS_FILE" ]; then
+              echo "Error: Main CSS file not found at $CSS_FILE"
               exit 1
             fi
 
-            CACHE_BUSTED_MD5_HASH=$(md5sum "$CACHE_BUSTED_CSS_FILE" | awk '{ print $1 }')
-            if [ "$MD5_HASH" != "$CACHE_BUSTED_MD5_HASH" ]; then
-              echo "Error: MD5 hash of the cache busted CSS file does not match the original"
+            if [ ! -f "$HTML_FILE" ]; then
+              echo "Error: Base HTML tempalte file not found at $HTML_FILE"
               exit 1
             fi
 
-            BASE_TEMPLATE="./src/views/base.html"
-            if ! grep -q "main.${MD5_HASH}.css" "$BASE_TEMPLATE"; then
-              echo "Error: Base template does not contain a reference to the cache busted CSS file"
+            HTML_HASH=$(grep -oP 'href="/assets/css/main\.css\?h=\K[a-f0-9]{32}' "$HTML_FILE")
+
+            if [ -z "$HTML_HASH" ]; then
+              echo "Error: Could not find CSS file reference with hash in $HTML_FILE"
               exit 1
             fi
 
-            echo "Verification successful: Cache busted CSS file exists, its content integrity is verified, and it is referenced in the base template"
+            if [ "$MD5_HASH" != "$HTML_HASH" ]; then
+              echo "Error: Hash mismatch"
+              echo "CSS file hash: $MD5_HASH"
+              echo "HTML reference hash: $HTML_HASH"
+              exit 1
+            fi
+
+            echo "Verification successful: Main CSS file hash matches the reference in $HTML_FILE"
 
 workflows:
   main:
